DROP PROCEDURE SUGGESTIONS;
DROP PROCEDURE OBJET_PREFERE;
DROP FUNCTION SCORE_OBJET;

DROP TRIGGER CHECK_THEME;
DROP TRIGGER LISTE_INSERT;
DROP TRIGGER UTILISATEUR_INSERT;
DROP TRIGGER TRIGGER_ARCHIVAGE;
DROP TRIGGER TRIGGER_NOUVEAUTES;

DROP TABLE OBJET_UTILISATEUR;
DROP TABLE OBJET_LISTE;
DROP TABLE OBJET_LISTE_ARCHIVE;
DROP TABLE ARCHIVE_LISTE;
DROP TABLE LISTE;
DROP TABLE OBJET;
DROP TABLE UTILISATEUR;

DROP SEQUENCE seq_id_Utilisateur;
DROP SEQUENCE seq_id_ListeArchive;
DROP SEQUENCE seq_id_Liste;
